server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://unleashwell.online"
              - "https://www.unleashwell.online"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
            maxAge: 3600
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/public/**

        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**


        - id: user-service-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter

        - id: consultation-service
          uri: lb://CONSULTATION-SERVICE
          predicates:
            - Path=/consultation/**
          filters:
            - AuthenticationFilter

        - id: consultation-service
          uri: lb://CONSULTATION-SERVICE
          predicates:
            - Path=/plan/**

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article/public/**

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article/**
          filters:
            - AuthenticationFilter

        - id: websocket_route
          uri: lb:ws://CONSULTATION-SERVICE
          predicates:
            - Path=/ws/**


  application:
    name: UNLEASH-GATEWAY

