name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull docker image
        run:  docker pull adarsh6672/unleash-gatewayservice
      - name: delete old docker image
        run:  docker rm -f gateway-service || true
      - name: run docker container
        run:  docker run -d -p 8080:8080 --name gateway-service --network test_app-network adarsh6672/unleash-gatewayservice

